name: flutter_tex_example
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_tex: ^1.0.14
  cupertino_icons: ^0.1.2
  flutter_spinkit: "^4.1.1"
  webview_flutter: ^0.3.19+6

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
          #style: italic
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans.ttf
          
